# Generated by Django 4.0.3 on 2023-07-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('course', models.CharField(max_length=20)),
                ('session', models.CharField(blank=True, choices=[('Day', 'Day'), ('Evening', 'Evening'), ('Weekend', 'Weekend')], max_length=8, null=True)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(blank=True, max_length=25, null=True)),
                ('religion', models.CharField(max_length=20)),
                ('telephone_no', models.CharField(max_length=15)),
                ('nationality', models.CharField(blank=True, max_length=20, null=True)),
                ('marital_status', models.CharField(choices=[('M', 'Married'), ('S', 'Single')], max_length=2)),
            ],
        ),
    ]
