# Generated by Django 4.0.3 on 2023-07-18 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardno', models.CharField(default='', max_length=12, unique=True)),
                ('barcode', models.ImageField(blank=True, upload_to='barcodes/')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('De-activated', 'Deactivated'), ('Terminated', 'Terminated')], max_length=15)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.student')),
            ],
        ),
    ]
