# Generated by Django 4.1.3 on 2023-05-09 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0006_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('students_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cards.student')),
            ],
        ),
    ]
