# Generated by Django 4.1.3 on 2023-07-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0007_yourmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='Barcode',
            field=models.ImageField(blank=True, upload_to='barcodes/'),
        ),
        migrations.AddField(
            model_name='card',
            name='cardno',
            field=models.CharField(default='', max_length=12),
        ),
    ]
