# Generated by Django 4.1.3 on 2023-07-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0008_card_barcode_card_cardno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='Barcode',
            new_name='barcode',
        ),
        migrations.AlterField(
            model_name='card',
            name='cardno',
            field=models.CharField(default='', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='clearance',
            name='semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=2),
        ),
        migrations.AlterField(
            model_name='clearance',
            name='year_of_study',
            field=models.CharField(choices=[('1', '1yr'), ('2', '2yr'), ('3', '3yr'), ('4', '4yr')], max_length=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
