# Generated by Django 4.0.3 on 2023-07-16 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0009_rename_barcode_card_barcode_alter_card_cardno_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='card',
            table='card',
        ),
    ]
