# Generated by Django 4.0.3 on 2023-07-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0010_alter_card_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='barcode',
            field=models.CharField(default=2, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(choices=[('1', '1yr'), ('2', '2yr'), ('3', '3yr'), ('4', '4yr')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='card',
            table=None,
        ),
    ]
