# Generated by Django 4.0.3 on 2023-07-18 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0011_student_barcode_alter_course_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='barcode',
        ),
    ]
